// Generated by CoffeeScript 2.4.1
export default {
  img: {
    pictures: {
      nude_bg_leafs: require('../../assets/img/pictures/nude_bg_leafs.jpg'),
      nude_logo: require('../../assets/img/pictures/logo.png'),
      auto_nude_detection: require('../../assets/img/pictures/auto_nude_detection.png'),
      secure_vault: require('../../assets/img/pictures/secure_vault.png'),
      breakin_alerts: require('../../assets/img/pictures/breakin_alerts.png'),
      white_bottom_gradient: require('../../assets/img/pictures/white_bottom_gradient.png'),
      dark_bottom_gradient: require('../../assets/img/pictures/dark_bottom_gradient.png'),
      modal_scanning: require('../../assets/img/pictures/modal_scanning.png'),
      modal_plus: require('../../assets/img/pictures/modal_plus.png'),
      modal_plus_android: require('../../assets/img/pictures/modal_plus_android.png'),
      progress_circle_bg: require('../../assets/img/pictures/progress_circle_bg.png'),
      progress_circle_center: require('../../assets/img/pictures/progress_circle_center.png'),
      keyboard: {
        one: require('../../assets/img/pictures/keyboard/1.png'),
        two: require('../../assets/img/pictures/keyboard/2.png'),
        three: require('../../assets/img/pictures/keyboard/3.png'),
        four: require('../../assets/img/pictures/keyboard/4.png'),
        five: require('../../assets/img/pictures/keyboard/5.png'),
        six: require('../../assets/img/pictures/keyboard/6.png'),
        seven: require('../../assets/img/pictures/keyboard/7.png'),
        eight: require('../../assets/img/pictures/keyboard/8.png'),
        nine: require('../../assets/img/pictures/keyboard/9.png'),
        c: require('../../assets/img/pictures/keyboard/C.png'),
        zero: require('../../assets/img/pictures/keyboard/0.png'),
        back: require('../../assets/img/pictures/keyboard/BACK.png')
      }
    },
    icons: {
      back_arrow: require('../../assets/img/icons/back_arrow.png'),
      fs_access: require('../../assets/img/icons/fs_access.png'),
      camera_access: require('../../assets/img/icons/camera_access.png'),
      thin_cross: require('../../assets/img/icons/thin_cross.png'),
      three_dots: require('../../assets/img/icons/three_dots.png'),
      grid_view: require('../../assets/img/icons/grid_view.png'),
      list_view: require('../../assets/img/icons/list_view.png'),
      gallery_view: require('../../assets/img/icons/gallery_view.png'),
      video_view: require('../../assets/img/icons/video_view.png'),
      forward_arrow: require('../../assets/img/icons/forward_arrow.png'),
      success: require('../../assets/img/icons/success.png'),
      break_in: require('../../assets/img/icons/break_in.png'),
      trash: require('../../assets/img/icons/trash.png'),
      trash_white: require('../../assets/img/icons/trash_white.png'),
      trash_2: require('../../assets/img/icons/trash_2.png'),
      touch_id: require('../../assets/img/icons/touch_id.png'),
      face_id: require('../../assets/img/icons/face_id.png'),
      plus: require('../../assets/img/icons/plus.png'),
      image: require('../../assets/img/icons/image.png'),
      video: require('../../assets/img/icons/video.png'),
      video_linear_icon: require('../../assets/img/icons/video_linear_icon.png'),
      trash_linear_icon: require('../../assets/img/icons/trash_linear_icon.png'),
      trash_linear_icon_grey: require('../../assets/img/icons/trash_linear_icon_grey.png'),
      share_linear_icon: require('../../assets/img/icons/share_linear_icon.png'),
      share_linear_icon_grey: require('../../assets/img/icons/share_linear_icon_grey.png'),
      export_linear_icon: require('../../assets/img/icons/export_linear_icon.png'),
      export_linear_icon_grey: require('../../assets/img/icons/export_linear_icon_grey.png'),
      scanning_picture: require('../../assets/img/icons/scanning_picture.png'),
      selected: require('../../assets/img/icons/selected.png'),
      add_media: require('../../assets/img/icons/add_media.png'),
      camera: require('../../assets/img/icons/camera.png'),
      loading: require('../../assets/img/icons/loading.png')
    }
  }
};

//# sourceMappingURL=assets.js.map
