// Generated by CoffeeScript 2.4.1
import React, {
  Component,
  PureComponent
} from 'react';

import {
  createContext
} from 'react';

import _ from 'underscore';

import moment from 'moment';

import {
  AppState,
  AsyncStorage,
  CameraRoll,
  NativeModules,
  Platform,
  BackHandler,
  Share,
  Dimensions,
  StyleSheet,
  StatusBar,
  Alert,
  Linking,
  Animated,
  Text,
  View,
  Image,
  ImageBackground,
  TouchableOpacity,
  TouchableHighlight,
  Button,
  TextInput,
  Switch,
  ScrollView,
  FlatList,
  Shadow
} from 'react-native';

import NetInfo from '@react-native-community/netinfo';

import {
  withNavigation,
  withNavigationFocus
} from 'react-navigation';

import Constants from 'expo-constants';

import {
  SplashScreen,
  ScreenOrientation
} from 'expo';

import * as Permissions from 'expo-permissions';

import * as Font from 'expo-font';

import {
  LinearGradient
} from 'expo-linear-gradient';

import * as LocalAuth from 'expo-local-authentication';

import * as Sharing from 'expo-sharing';

import {
  Video
} from 'expo-av';

import * as ImagePicker from 'expo-image-picker';

import * as ImageManipulator from 'expo-image-manipulator';

import * as FileSystem from 'expo-file-system';

import * as MediaLibrary from 'expo-media-library';

import {
  Camera
} from 'expo-camera';

import {
  State,
  PinchGestureHandler,
  LongPressGestureHandler
} from 'react-native-gesture-handler';

import {
  Hybrid,
  API,
  Ambry
} from '../imports/genius/hybrid';

import Assets from './assets';

import Typography from '../imports/ui/shape/typography';

import Theme from '../imports/ui/shape/theme';

import random from 'randomatic';

this.React = React;

this.Component = Component;

this.PureComponent = PureComponent;

this.createContext = createContext;

this._ = _;

this.moment = moment;

this.AppState = AppState;

this.AsyncStorage = AsyncStorage;

this.CameraRoll = CameraRoll;

this.NativeModules = NativeModules;

this.Platform = Platform;

this.BackHandler = BackHandler;

this.Share = Share;

this.Dimensions = Dimensions;

this.StyleSheet = StyleSheet;

this.StatusBar = StatusBar;

this.Alert = Alert;

this.Linking = Linking;

this.Animated = Animated;

this.Text = Text;

this.View = View;

this.Image = Image;

this.ImageBackground = ImageBackground;

this.TouchableOpacity = TouchableOpacity;

this.TouchableHighlight = TouchableHighlight;

this.Button = Button;

this.TextInput = TextInput;

this.Switch = Switch;

this.ScrollView = ScrollView;

this.FlatList = FlatList;

this.Shadow = Shadow;

this.NetInfo = NetInfo;

this.withNavigation = withNavigation;

this.withNavigationFocus = withNavigationFocus;

this.Constants = Constants;

this.SplashScreen = SplashScreen;

this.ScreenOrientation = ScreenOrientation;

this.Permissions = Permissions;

this.Font = Font;

this.LinearGradient = LinearGradient;

this.LocalAuth = LocalAuth;

this.Sharing = Sharing;

this.Video = Video;

this.ImagePicker = ImagePicker;

this.ImageManipulator = ImageManipulator;

this.FileSystem = FileSystem;

this.MediaLibrary = MediaLibrary;

this.Camera = Camera;

this.GestureState = State;

this.PinchGestureHandler = PinchGestureHandler;

this.LongPressGestureHandler = LongPressGestureHandler;

this.Hybrid = Hybrid;

this.API = API;

this.Ambry = Ambry;

this.Assets = Assets;

this.Typography = Typography;

this.Theme = Theme;

this.random = random;

this.WebsiteAddress = 'https://thenudeapp.com';

this.Window = Dimensions.get('window');

//# sourceMappingURL=global_scope.js.map
