// Generated by CoffeeScript 2.4.1
var Ambry, Hybrid, States;

import {
  connect
} from 'react-redux';

import Hunter from './hunter';

Hunter();

import API from './api/kit';

States = function(state, props) {
  return {...state};
};

Hybrid = function(component) {
  return connect(States, null)(component);
};

Ambry = {
  state: () => {
    return STORE.getState();
  },
  call: (id, data) => {
    if (data === void 0) {
      return STORE.dispatch({
        type: id
      });
    } else {
      return STORE.dispatch({
        type: id,
        data: data
      });
    }
  }
};

export {
  Hybrid,
  API,
  Ambry
};

//# sourceMappingURL=hybrid.js.map
