// Generated by CoffeeScript 2.4.1
import {
  combineReducers
} from 'redux';

import app from './boxes/app';

export default () => {
  return combineReducers({
    app: app
  });
};

//# sourceMappingURL=redux.js.map
