// Generated by CoffeeScript 2.4.1
var HelpPage, Shape, _class,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

HelpPage = _class = class extends PureComponent {
  constructor(props) {
    super(props);
    this.render = this.render.bind(this);
    this.state = {
      content: this.props.navigation.getParam('help_page_content')
    };
  }

  render() {
    boundMethodCheck(this, _class);
    return <View style={Shape.Box}>
      <Text style={[Typography.Medium, Typography.Regular, Typography.Grey, Shape.Title]}>{this.state.content.title}</Text>
      <ScrollView style={Shape.ContentBox}>
        <Text style={[Typography.Medium, Typography.Regular, Typography.DarkGrey]}>{this.state.content.content}</Text>
      </ScrollView>
      <Text style={[Typography.Medium, Typography.Little, Typography.Grey, Shape.BottomText]}>Updated July 23, 2019</Text>
    </View>;
  }

};

Shape = StyleSheet.create({
  Box: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    paddingHorizontal: 30,
    backgroundColor: '#F5F6F9'
  },
  Title: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center'
  },
  ContentBox: {
    width: Window.width - 60,
    height: '90%',
    marginVertical: 20,
    marginHorizontal: 30,
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderRadius: 16,
    backgroundColor: 'white'
  },
  BottomText: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center'
  }
});

export default Hybrid(HelpPage);

//# sourceMappingURL=help_page.js.map
