// Generated by CoffeeScript 2.4.1
import './lib/initial_script';

import './lib/global_scope';

import {
  Provider
} from 'react-redux';

import {
  createStore,
  applyMiddleware
} from 'redux';

import Redux from './imports/genius/redux';

import App from './imports/kit';

this.STORE = createStore(Redux());

export default () => {
  return <Provider store={STORE}>
    <App />
  </Provider>;
};

//# sourceMappingURL=kit.js.map
