// Generated by CoffeeScript 2.4.1
var BGGradient, Shape, _class,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

BGGradient = _class = class extends PureComponent {
  constructor(props) {
    super(props);
    this.render = this.render.bind(this);
  }

  render() {
    boundMethodCheck(this, _class);
    return <LinearGradient pointerEvents='box-none' colors={this.props.colors} style={this.props.style ? [Shape.BGGradient, this.props.style] : Shape.BGGradient} start={this.props.start ? this.props.start : [1, 0]} end={this.props.end ? this.props.end : [0, 1]}>
      {this.props.children}
    </LinearGradient>;
  }

};

Shape = StyleSheet.create({
  BGGradient: {
    width: Window.width,
    height: Window.height
  }
});

export default Hybrid(BGGradient);

//# sourceMappingURL=bg_gradient.js.map
