// Generated by CoffeeScript 2.4.1
var HeaderLogo, Shape, _class,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

import NudeLogo from './nude_logo';

HeaderLogo = _class = class extends PureComponent {
  constructor(props) {
    super(props);
    this.render = this.render.bind(this);
  }

  render() {
    boundMethodCheck(this, _class);
    return <View style={Shape.Box}>
      <NudeLogo />
    </View>;
  }

};

Shape = StyleSheet.create({
  Box: {
    width: 106,
    height: 48,
    alignItems: 'center'
  }
});

export default Hybrid(HeaderLogo);

//# sourceMappingURL=header_logo.js.map
