// Generated by CoffeeScript 2.4.1
var HeaderCustomBack, _class,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

HeaderCustomBack = _class = class extends PureComponent {
  constructor(props) {
    super(props);
    this.press = this.press.bind(this);
    this.render = this.render.bind(this);
  }

  press() {
    boundMethodCheck(this, _class);
    if (this.props.action === 'goHome') {
      return this.props.navigation.navigate('Home');
    } else {
      return this.props.navigation.goBack();
    }
  }

  render() {
    boundMethodCheck(this, _class);
    return <TouchableOpacity onPress={this.press}>
      <Image source={Assets.img.icons.back_arrow} style={{
        width: 18,
        height: 18,
        marginLeft: 13,
        resizeMode: 'contain'
      }} />
    </TouchableOpacity>;
  }

};

export default Hybrid(withNavigation(HeaderCustomBack));

//# sourceMappingURL=header_custom_back.js.map
