// Generated by CoffeeScript 2.4.1
var ImportNotification, Shape, _class,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

import BGGradient from './bg_gradient';

ImportNotification = _class = class extends PureComponent {
  constructor(props) {
    super(props);
    this.delete = this.delete.bind(this);
    this.cancel = this.cancel.bind(this);
    this.render = this.render.bind(this);
  }

  delete() {
    var objects;
    boundMethodCheck(this, _class);
    objects = this.props.app.import_notification.objects;
    return API.global.removeMediaFromLibrary(objects, () => {
      if (Platform.OS === 'ios') {
        return Alert.alert('ONE MORE THING', 'Don\'t forget to delete your photos from the "Recently Deleted" album in your Camera Roll 😉', [
          {
            text: 'Ok',
            onPress: () => {
              return this.cancel();
            }
          }
        ]);
      } else {
        return this.cancel();
      }
    });
  }

  cancel() {
    boundMethodCheck(this, _class);
    Ambry.call('setImportNotification', {
      visible: false,
      objects: []
    });
    return API.global.lastScanning('finish');
  }

  render() {
    boundMethodCheck(this, _class);
    return <BGGradient colors={['#574B90', '#FC85AE']} style={{
        width: '100%',
        height: '100%'
      }}>
      <View style={Shape.Box}>
        <TouchableOpacity style={Shape.Cancel} activeOpacity={.7} onPress={this.cancel}>
          <Image source={Assets.img.icons.plus} style={{
        width: 16,
        height: 16,
        resizeMode: 'contain'
      }} />
        </TouchableOpacity>
        <Text style={[Typography.Medium, Typography.Small]}>
          {(Platform.OS === 'ios' ? "Import complete. Delete from\nCamera Roll?" : "Import complete. Delete from\nGallery?")}
        </Text>
        <TouchableOpacity style={Shape.Delete} activeOpacity={.7} onPress={this.delete}>
          <Image source={Assets.img.icons.trash_white} style={{
        width: 24,
        height: 24,
        resizeMode: 'contain',
        marginBottom: 5
      }} />
          <Text style={[Typography.Light, Typography.Little]}>Delete</Text>
        </TouchableOpacity>
      </View>
    </BGGradient>;
  }

};

Shape = StyleSheet.create({
  Box: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    height: '100%',
    paddingVertical: 16,
    paddingHorizontal: 24,
    paddingLeft: 12
  },
  Cancel: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [
      {
        rotate: '45deg'
      }
    ],
    padding: 10
  },
  Delete: {
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 5
  }
});

export default Hybrid(ImportNotification);

//# sourceMappingURL=import_notification.js.map
