// Generated by CoffeeScript 2.4.1
var MenuButton, _class,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

MenuButton = _class = class extends PureComponent {
  constructor(props) {
    super(props);
    this.openMenu = this.openMenu.bind(this);
    this.render = this.render.bind(this);
  }

  openMenu() {
    boundMethodCheck(this, _class);
    return this.props.navigation.openDrawer();
  }

  render() {
    boundMethodCheck(this, _class);
    return <TouchableOpacity style={{
        width: 36,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center'
      }} onPress={this.openMenu}>
      <Image source={Assets.img.icons.three_dots} style={{
        width: 24,
        height: 24,
        resizeMode: 'contain'
      }} />
    </TouchableOpacity>;
  }

};

export default Hybrid(withNavigation(MenuButton));

//# sourceMappingURL=menu_button.js.map
