// Generated by CoffeeScript 2.4.1
var NudeLogo, _class,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

NudeLogo = _class = class extends PureComponent {
  constructor(props) {
    super(props);
    this.render = this.render.bind(this);
  }

  render() {
    boundMethodCheck(this, _class);
    return <Image source={Assets.img.pictures.nude_logo} style={{
        width: '100%',
        height: '100%',
        resizeMode: 'contain'
      }} />;
  }

};

export default Hybrid(NudeLogo);

//# sourceMappingURL=nude_logo.js.map
